### ISSUE TITLE
A new dataset paper

### ISSUE THREAD

**Issue by hqqxyy** [bcmi/Awesome-Aesthetic-Evaluation-and-Cropping#2]
Hi,

Thanks for your amazing work. I found a new dataset paper 

Kang, Chen, Giuseppe Valenzise, and Frédéric Dufaux. "EVA: An Explainable Visual Aesthetics Dataset." Joint Workshop on Aesthetic and Technical Quality Assessment of Multimedia and Media Analytics for Societal Trends. 2020.

They also released their dataset at https://github.com/kang-gnak/eva-dataset.

Thanks,

**Comment by ustcnewly** [comment]
done
